[tool.poetry]
name = "boring"
version = "0.1.0"
description = ""
authors = ["Xesxer-cn"]

[tool.poetry.dependencies]
python = "3.8.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
